spring:
  application:
    name: DubboProvider
server:
    port: 9100
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 9200
  registry:
    id: zk-registry
    address: zookeeper://localhost:2181
  config-center:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181